### Hämta alla användare
GET http://localhost:3000/api/users

### Hämta en specifik användare
GET http://localhost:3000/api/users/6746e0fab030939318458061

### Skapa en ny användare
POST http://localhost:3000/api/users/create
Content-Type: application/json

{
    "firstname": "Hugo",
    "lastname": "Roque",
    "username": "hugohugo",
    "password": "123456"
}

### Ta bort en användare
DELETE http://localhost:3000/api/users/6746e0fab030939318458061

### Uppdatera en användare
PUT http://localhost:3000/api/users/67471a2e010696a45c5c713c
Content-Type: application/json

{
    "username": "Jessica",
    "password": "superpassword"
}