### Hämta alla användare
GET http://localhost:3000/api/users

### Ta bort en användare
DELETE http://localhost:3000/api/users/6748b7e7971030f72222e07a


### Hämta en specifik användare
GET http://localhost:3000/api/users/6746e0fab030939318458061

### Skapa en ny användare
POST http://localhost:3000/api/users/create
Content-Type: application/json

{
    "firstname": "Alexander",
    "lastname": "Alexander",
    "username": "Alexander",
    "password": "Alexander"
}



### Uppdatera en användare
PUT http://localhost:3000/api/users/6747617fdf2ebf65c9f12220
Content-Type: application/json

{
    "username": "Jessica",
    "password": "superpassword"
}

### Logga in
POST http://localhost:3000/api/users/login
Content-Type: application/json

{
    "username": "DianitaDianita",
    "password": "DianitaDianita"
}

### LOGOUT A USER
POST http://localhost:3000/api/users/logout